### ISSUE TITLE
Spec tests are failing for rocky 8

### ISSUE THREAD

**Issue by rgardner4012** [simp/pupmod-simp-tpm#92]
Seeing the following errors on spec tests currently:
  20) tpm::tboot on rocky-8-x86_64 sinit over rsync is expected to contain File[/boot/2nd_gen_i5_i7_SINIT_51.BIN] with source => "/root/txt/sinit/2nd_gen_i5_i7_SINIT_51.BIN"
      Failure/Error: it { is_expected.to contain_file('/boot/2nd_gen_i5_i7_SINIT_51.BIN').with_source('/root/txt/sinit/2nd_gen_i5_i7_SINIT_51.BIN') }

      Puppet::PreformattedError:
        Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Package name must be formatted as Yum::RpmName, not 'String'. See Yum::Rpmname documentation for details. (file: /Users/rgardner/projects/puppetsync/_repos/pupmod-simp-tpm/spec/fixtures/modules/yum/manifests/versionlock.pp, line: 80, column: 7) (file: /Users/rgardner/projects/puppetsync/_repos/pupmod-simp-tpm/spec/fixtures/modules/tpm/manifests/tboot/lock_kernel.pp, line: 16) on node ricks-mbp-work.localdomain
      # /opt/puppetlabs/bolt/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
      # ./spec/classes/tboot_spec.rb:142:in `block (5 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # Puppet::ParseError:
      #   Package name must be formatted as Yum::RpmName, not 'String'. See Yum::Rpmname documentation for details.
      #   /opt/puppetlabs/bolt/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'

Finished in 57.63 seconds (files took 2 seconds to load)
245 examples, 20 failures

The next place to look for rocky specific failures is the following fixtures:
 concat: https://github.com/simp/puppetlabs-concat.git
    ima: https://github.com/simp/pupmod-simp-ima.git
    rsync: https://github.com/simp/pupmod-simp-rsync.git

**Comment by rgardner4012** [comment]
TPM module doesn't support el8 boxes, use tpm2 for this.
